import Card from "./Card"

export default function Section_card(){
    return(
        <section>
            <div>
                <Card
                    type='titre'
                    url={'../assets/image-jeremy.png'}
                    nom={"Robson"}
                    prenom={'Jeremy'}
                />
            </div>
            <div>
                <Card
                    type={'clasique'}
                    titre={'Work'}
                    time={32}
                    last={36}
                    mode={'week'}
                />
                <Card
                    type={'clasique'}
                    titre={'Play'}
                    time={10}
                    last={8}
                    mode={'week'}
                />
                <Card
                    type={'clasique'}
                    titre={'Study'}
                    time={4}
                    last={7}
                    mode={'week'}
                />
                <Card
                    type={'clasique'}
                    titre={'Exercise'}
                    time={4}
                    last={5}
                    mode={'week'}
                />
                <Card
                    type={'clasique'}
                    titre={'Social'}
                    time={5}
                    last={10}
                    mode={'week'}
                />
                <Card
                    type={'clasique'}
                    titre={'Self Care'}
                    time={2}
                    last={2}
                    mode={'week'}
                />
            </div>
        </section>
    )
}